// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWl7qEj3N37nGH43xouRxomtaKRvmsSRg',
    appId: '1:804953251971:web:64511ff13c8eb34d657bb6',
    messagingSenderId: '804953251971',
    projectId: 'travel-app-49061',
    authDomain: 'travel-app-49061.firebaseapp.com',
    storageBucket: 'travel-app-49061.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLB7hi2GAphoKaYkymuAFopBTapfnzifo',
    appId: '1:804953251971:android:3d98a07ce420a1e5657bb6',
    messagingSenderId: '804953251971',
    projectId: 'travel-app-49061',
    storageBucket: 'travel-app-49061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUAyfexrBTEOQLmrqo0Nx-NjEYsQcgGcI',
    appId: '1:804953251971:ios:fd5b705d00340d7e657bb6',
    messagingSenderId: '804953251971',
    projectId: 'travel-app-49061',
    storageBucket: 'travel-app-49061.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUAyfexrBTEOQLmrqo0Nx-NjEYsQcgGcI',
    appId: '1:804953251971:ios:fd5b705d00340d7e657bb6',
    messagingSenderId: '804953251971',
    projectId: 'travel-app-49061',
    storageBucket: 'travel-app-49061.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWl7qEj3N37nGH43xouRxomtaKRvmsSRg',
    appId: '1:804953251971:web:e4333514fb93a4ef657bb6',
    messagingSenderId: '804953251971',
    projectId: 'travel-app-49061',
    authDomain: 'travel-app-49061.firebaseapp.com',
    storageBucket: 'travel-app-49061.firebasestorage.app',
  );
}
